#!/usr/bin/env sh

INPUT_YAML="./api-spec.yaml"
OUTPUT="./src/types/api"

# Fetch OpenAPI spec
curl -o $INPUT_YAML $OPEN_API_SPEC_URL >/dev/null 2>&1

# Check if curl command was successful
if [ $? -ne 0 ]; then
    echo "Error: Failed to fetch OpenAPI spec."
    exit 1
fi

# Generate types from OpenAPI spec
pnpm exec openapi-typescript $INPUT_YAML -o $OUTPUT/schema.d.ts >/dev/null 2>&1

# Check if generation was successful
if [ $? -ne 0 ]; then
    echo "Error: Failed to generate types from OpenAPI spec."
    exit 1
fi

echo "Process completed successfully."
